  name: GitHub Actions Demo
  on: [ push ]
  jobs:
    DeployScreepsCode:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Deploying Screeps code for all files listed in screeps.yml"
        - name: Screeps Deployer
          uses: aphistic/screeps-deployer@v0.1.0
